# Generated by Django 4.0.2 on 2022-04-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
