# Generated by Django 4.0.4 on 2022-04-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscribers', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
