# Generated by Django 4.0.4 on 2022-04-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
